# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Blog of AnneLiu
email: 869491672@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Don't forget to be awesome.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://annetaliu.github.io" # the base hostname & protocol for your site
twitter_username: anneliu2012
github_username:  annetaliu

# Build settings
markdown: kramdown
